server:
        port: 8989 # 内嵌的 Tomcat 端口号。默认值为 8080。
logging:
  config: classpath:log4j2-spring.xml
  level:
    cn.jay.repository: trace
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=false
    username: root
    password: ""
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false #关闭缓存
mybatis:
  type-aliases-package: com.lxy.demo01.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# PageHelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true